version: "3.9"
services:
  web:
    image: "alekseikanash/web_service_weather"
    container_name: web_service
    env_file: 
      - $HOME/.slack/.env
    ports:
      - "8080:80"

  bot:
    image: "alekseikanash/slack_bot_service_weather"
    env_file: 
      - $HOME/.slack/.env

  postgres:
    image: postgres
    container_name: posgtres
    restart: always
    environment:
      - POSTGRES_USER=adm
      - POSTGRES_PASSWORD=adm
      - POSTGRES_DB=weather
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes: 
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

